keys:
  - &sam_1 9B67D6590E23977B0A9DFA8599BAB942A14EBDB3
  - &sam_2 B4A248648984241714F8D9004B3F6BF94BF93F25
  - &sam_age age1t5se2cjfsh5wut26k8yvma39zvahsmynmck7ewacp4zh02zyhpaqzv4eez
  - &krypton age1fgrjnfensm48a5pl5kqvn7llhmauhjqqskl8h8le3ql93zp3e5es4yr4wd
  - &iodine age14xt89xj7tn85atu5udzuxkjf8vsy7efgnny4sufeggc35xj5yups34xm84
  - &aoi age15zdzuu88vgxkkzg8w75rw2pn7renfx7m8rlz2kflrf4x7je553es3nu7rm
  - &db-1 age15slpqakandq5g3lsl8hu79yk8vus5pxxvfzrsrvjfs77jv7yncwquv2mgx
  - &work-wsl age1lynr54j9mje7d6urchy7322vcqn9xr34t2l4976y0w20q29kl4jqpdgcte
creation_rules:
  - path_regex: users/\w+/secrets/[^/]+\.(yaml|json|env|ini|txt)$
    key_groups:
      - age: 
          - *krypton
          - *aoi
          - *work-wsl
          - *sam_age
          - *iodine
          - *db-1
        pgp:
          - *sam_1
          - *sam_2

  - path_regex: nodes/server/aoi/secrets/[^/]+\.(yaml|json|env|ini|pem)$
    key_groups:
      - age: 
          - *aoi
          - *sam_age
        pgp:
          - *sam_1
          - *sam_2

  - path_regex: nodes/desktop/iodine/secrets/[^/]+\.(yaml|json|env|ini|pem)$
    key_groups:
      - age: 
          - *iodine
          - *sam_age
        pgp:
          - *sam_1
          - *sam_2  

  - path_regex: nodes/desktop/work-wsl/secrets/[^/]+$
    key_groups:
      - age: 
          - *work-wsl
          - *sam_age
        pgp:
          - *sam_1
          - *sam_2
